name: Test-Deploy

# on: [push]
on: 
  push:
    branches:
        - test

jobs:
    init:
        runs-on: ubuntu-latest

        steps:
        - name: Initialication
          run: echo "Hello World!"
        - name: Validation
          run:
            echo "Add"
            echo "test"

    validate:
        runs-on: ubuntu-latest
        needs: [init]

        steps:
        - name: Validation
          run: echo "Hello Everyone!"
